config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  get "confirm", to: "toppages#pass"
  post "confirm", to: "toppages#confirm"

  get "borrow", to: "lists#new"
  post "lists", to: "lists#create"
  get "lists", to: "lists#relode"
  get "control", to: "lists#all"
  get "ipad", to: "lists#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :attendance, presence: true, length: { maximum: 4 },
                    format: { with: /\A\d{1}[a-z]\d{1,2}\z/i }
  validates :number, presence: true, length: { maximum: 3 },
                    numericality: { less_than_or_equal_to: 100, greater_than_or_equal_to: 1 },
                    format: { with: /\A[1-9]\d*\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    
    if @list.save
      flash[:success] = "送信が完了しました"
      redirect_to root_path
    else
      flash.now[:danger] = "送信できませんでした"
      render :new
    end
  end
  
  def relode
    @list = List.new
    render :new
  end

  def all
  end

  def show
    @lists = List.where("number = ?", params[:number]).order(created_at: "DESC")
    @num = params[:number]
  end
end

private

def list_params
  params.require(:list).permit(:attendance, :number)
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
  
  def pass
  end
  
  def confirm
    if params[:seisoku] == "0913"
      redirect_to control_path
    elsif 
      flash.now[:danger] = "パスワードが違います"
      render :pass
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>iPad貸出管理簿</title>
    
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>

  <body>
    <%= render 'layouts/flash_messages' %>

    <div class="container">

    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/all.html.erb
<h3>iPadの管理番号を選ぶ</h3>

<b>
<div class="table-responsive">
<table class="table table-striped">
  <tr align="center">
    <% (1..10).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr>
  
  <tr align="center">
    <% (11..20).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr>
  
  <tr align="center">
    <% (21..30).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr>

  <tr  align="center">
    <% (31..40).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr>  
  
  <tr align="center">
    <% (41..50).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr>  
  
  <tr align="center">
    <% (51..60).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr>  
  
  <tr align="center">
    <% (61..70).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr> 
  
  <tr align="center">
    <% (71..80).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr> 
  
  <tr align="center">
    <% (81..90).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr> 
  
  <tr align="center">
    <% (91..100).each do |num| %>
      <td>
        <%= link_to num, ipad_path(number: num) %>
      </td>
    <% end %>
  </tr> 
  
</table>
</div>
</b>

<%= link_to "TOPに戻る", root_path, class: "btn btn-danger" %>

app/views/lists/new.html.erb
<div class="row">
<div class="col-sm-10 col-sm-offset-1">

<h3>iPadを借りる</h3>
    
<div class="panel panel-success">
	<div class="panel-heading">
		入力情報
	</div>
	<div class="panel-body">
		生徒番号とiPad管理番号を入力してください。
	</div>
</div>

<%= form_for(@list) do |f| %>

<div class="form-group">
  <%= f.label :attendance, "生徒番号" %>
  <%= f.text_field :attendance, class: "form-control", placeholder: "例）2F50"  %>
</div>

<div class="form-group">
<%= f.label :number, "iPad管理番号" %>
<%= f.number_field :number, class: "form-control", placeholder: "例）82" %>
</div>

<%= f.submit "送信", class: "btn btn-success" %>

<% end %>

</div>
</div>

app/views/lists/show.html.erb
<div class="row">
<div class="col-sm-10 col-sm-offset-1">

<h3>
  管理番号:<%= @num %>の貸出リスト
</h3>

<ul class="list-group">
  <% @lists.each do |list| %>
  <li class="list-group-item">
     【<%= list.attendance %>】：
      <%= list.created_at.to_s(:datetime_jp) %>
  </li>
  <% end %>
</ul>

<%= link_to "管理番号一覧に戻る", control_path, class: "btn btn-warning" %>
<%= link_to "TOPに戻る", root_path, class: "btn btn-danger" %>

</div>
</div>

app/views/toppages/index.html.erb
<div class="row">
<div class="col-sm-10 col-sm-offset-1">

<h3>iPad貸出管理簿</h3>
<div>
  <%= link_to "借りる", borrow_path, class: "btn btn-success btn-lg btn-block" %>
  <%= link_to "管理する", confirm_path, class: "btn btn-default btn-lg btn-block" %>
</div>


</div>
</div>

app/views/toppages/pass.html.erb
<br>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    
    <%= form_tag(confirm_path, method: :post) do %>
    <div class="form-group">
      <%= label_tag :パスワード %>
      <%= text_field_tag :seisoku, "", class: "form-control" %>
    </div>

    <%= submit_tag "送信", class: "btn btn-info" %>
    <% end %>

  </div>
</div>